#!/usr/bin/python2
import os
def root_check():                                 # Function to determine if program runs as root
	a=os.popen('whoami').read()		  # Using whoami command
	if (a[:-1]=='root'):			  # Check with the real value
		return 1                          # Returning 1 if the user is root
	else:					  # Returning 0 is the user is any other
    return 0 # '' '' '' '' '' '' '' '' '' '' '' ''
if root_check()==1 :
  os.system('export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g" && ./prebuilts/sdk/tools/jack-admin kill-server && ./prebuilts/sdk/tools/jack-admin start-server')
  print "Done! Jack fixed!"
else :
  print "You are not root! Please run this program as root."
