#!/usr/bin/python2
import os
def root_check():                                 # Function to determine if program runs as root
	a=os.popen('whoami').read()		  # Using whoami command
	if (a[:-1]=='root'):			  # Check with the real value
		return 1                          # Returning 1 if the user is root
	else:					  # Returning 0 is the user is any other
		return 0 # '' '' '' '' '' '' '' '' '' '' '' ''
print __file__+" v3"
if root_check()==1 :
	if(os.path.exists(".repo")):
		print ".repo exists checking for executable"
		if (os.path.exists("./prebuilts/sdk/tools/jack-admin")):
			if (os.path.exists(os.path.expanduser("~/.jack-server")) and os.path.exists(os.path.expanduser("~/.jack-settings"))):
				print "Jack executable found in ./prebuilts/sdk/tools/jack-admin"
				os.system('./prebuilts/sdk/tools/jack-admin kill-server')
				os.system('./prebuilts/sdk/tools/jack-admin start-server')
				os.system('./prebuilts/sdk/tools/jack-admin kill-server')
				os.system('export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g" && ./prebuilts/sdk/tools/jack-admin start-server')
				print "Jack should be fixed now. If issue persists try starting jack server manually and running this program"
			else :
				print "ERROR:Jack is not installed in your home directory"
		else :
			print "ERROR:Jack is not found in your rom sdk, make sure you have jack executable in ./prebuilts/sdk/tools/jack-admin "
	else :
		print "ERROR:This does not appear to be repo initialized directory"
else :
	print "ERROR:You are not root! Please run this program as root."
